version: '3.8'

services:
  service_db:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: service_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5555:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    build:
      context: .
      target: development
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./.env.development:/app/.env.development
      - ./next.config.ts:/app/next.config.ts
    ports:
      - '3000:3000'
    depends_on:
      - service_db
    env_file:
      - .env
